### ISSUE TITLE
`client_id` as query param in `/app/login` while it is being read from a conf file in `app/callback` endpoint

### ISSUE THREAD

**Issue by kasir-barati** [FusionAuth/fusionauth-javascript-sdk-express#11]
Hi dear reader,

First and foremost I really like to express my thanks for this repo and its intuitive, self explanatory codebase. I am right now [implementing my own backend app utilizing NestJS](https://github.com/kasir-barati/you-say) and was using this repo as ref, but I was wondering about one thing and I could wrap my head around it. You might be able to shed some lights on the matter, I've asked it [here, in FusionAuth lovely forum](https://fusionauth.io/community/forum/post/7191) and inspite my question and searches I could find the answer I am looking for. So can you please answer it there or here?

Best regards.

**Comment by kasir-barati** [comment]
So why I created this issue? I thought we might be able to add it to `README.md` in order to prevent future confusion for other devs who are using this repo as a reference to implement their own backend.

**Comment by JakeLo123** [comment]
Thanks for your question, @kasir-barati!

If I understand correctly, you are asking why the example server's [`GET /app/callback`](https://github.com/FusionAuth/fusionauth-javascript-sdk-express?tab=readme-ov-file#get-appcallback) is sending the client id param to `/oauth2/token`. It's because `client_id` is a required parameter for [`/oauth2/token`](https://fusionauth.io/docs/v1/tech/oauth/endpoints#complete-the-authorization-code-grant-request). It's the same value as the applicationId your fusionauth instance was configured with.

The React SDK doesn't call `GET /app/callback` on your server--fusionauth does. This is why the client id cannot be pulled from request query params like [`GET /app/login`](https://github.com/FusionAuth/fusionauth-javascript-sdk-express/blob/main/routes/login.js#L12)

If there is a way you think we can improve the documentation, feedback is very welcome!

On an unrelated note... I did notice an issue in the README for [`GET /app/callback`](https://github.com/FusionAuth/fusionauth-javascript-sdk-express?tab=readme-ov-file#get-appcallback). Step number 7 is incorrect--that should does not call `/oauth2/userinfo`. I recommend we remove this from the README. [Here is a PR to do so](https://github.com/FusionAuth/fusionauth-javascript-sdk-express/pull/12).

**Comment by kasir-barati** [comment]
Thanks @JakeLo123 for prompt reply, 

So first let me point out that I know why we need `client_id` in `GET /app/callback`.

Actually I was wondering so if that is the case that we have to eventually read the `client_id` from our config file in our backend RESTful API why bother to send it in `GET /app/login`. I mean it is just an extra prop that we are sending from our frontend and could prove to be useful if we were attaching the `client_id` to the response's cookie so that we could reuse the same `client_id`.

**Comment by kasir-barati** [comment]
This way we could have send different `client_id`s from our frontend app and be more flexible in backend.

BTW sorry for closing and reopening the issue. I just hit `CTRL + Enter` and it closed it.

**Comment by JakeLo123** [comment]
> This way we could have send different `client_id`s from our frontend app and be more flexible in backend.

It's my understanding that a fusionauth instance is configured with a single `applicationId`, but if you wanted to do something like you're describing you may update that `clientId` prop given for your FusionAuthProvider. The provider will update with whatever props you give it.

As for your server implementation. This repo is just an example--you may, of course, write any implementation that fits your needs.

**Comment by kasir-barati** [comment]
hmm, but then would the [`@fusionauth/react-sdk`](https://github.com/FusionAuth/fusionauth-javascript-sdk/tree/main/packages/sdk-react) work? I found out that we have a SDK for react and decided to use that to not reinvent the wheel. So far I could not find any validation in that codebase, but now that I read [this section](https://www.npmjs.com/package/@fusionauth/react-sdk#overview) it is saying:
> If you are hosting your own server, [see server code requirements](https://github.com/FusionAuth/fusionauth-javascript-sdk-express#server-code-requirements).

And then when I read the `GET /app/login/` it is not saying anything about `client_id` at all :sweat_smile::
> This endpoint must:
>
> 1. Generate PKCE code.
> 2. The code verifier should be saved in a secure HTTP-only cookie.
>      - The code challenge is passed along
>      - Encode and save `redirect_url` from the client app to `state`.
> 3. Redirect browser to `/oauth2/authorize` with a `redirect_uri` to `/app/token-exchange`

But I think it would be really helpful to see that it [`clientID` is optional here](https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/src/providers/FusionAuthProvider.tsx#L40). 

I know that that lib is archived now and the new repo is this one: https://github.com/FusionAuth/fusionauth-javascript-sdk/tree/main/packages/sdk-react

but there I also could see that `clientID` is mandatory. Also in [npm](https://www.npmjs.com/package/@fusionauth/react-sdk) the link is for the archived repo.

**Comment by JakeLo123** [comment]
>  in [npm](https://www.npmjs.com/package/@fusionauth/react-sdk) the link is for the archived repo.

Thank you for pointing out those stale links! Filed an issue with those: https://github.com/FusionAuth/fusionauth-javascript-sdk/issues/66

The prop is require because it's needed for all SDK functionality unless you have a custom server implementation that gets it from elsewhere. If you want to opt out of consuming that param from the React SDK, you can pass an empty string and ignore it on your server.

**Comment by kasir-barati** [comment]
I do not feel really comfortable to pass an empty string to that, also there might be future development. So personally I prefer to go with the flow and if in the future it changed or our codebase demanded we will try to come up with something.

But nevertheless thanks for clarifying it that we can pass empty string and be safe as long as our backend implementation is customized :slightly_smiling_face:.

Thanks for baring with my questions and clarifying them. Love to work with tools that have exemplary and excellent support.

I believe we can close this issue for now since the object which was clarification regarding `client_id` is completed IMHO.

Or do you have any other point that you wanna add @JakeLo123, if not you/I can close this issue.

Many thanks once more for the awesome support.

**Comment by JakeLo123** [comment]
> But nevertheless thanks for clarifying it that we can pass empty string and be safe as long as our backend implementation is customized 🙂.

Yes [`/oauth/authorize`](https://fusionauth.io/docs/lifecycle/authenticate-users/oauth/endpoints#authorize) is the thing that requires `client_id`, so however your server gets it there should be okay. This example server is at parity with the FusionAuth hosted endpoints, which do require it.

Ok, we'll close this here. Thanks for your help as well 🙌
